version: '2'
services:
  datastore:
    image: busybox
    volumes:
      - node_modules:/myapp/node_modules
  main:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - dsync:/myapp
    command: yarn start

volumes:
  node_modules:
    driver: local
  dsync:
    external: true
