version: '2'
services:
  datastore:
    image: busybox
    volumes:
      - node_modules:/myapp/node_modules
  main:
    container_name: base
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/myapp
    command: /bin/sh

volumes:
  node_modules:
    driver: local
