FROM ubuntu:16.04

RUN set -x \
&&  apt-get -y update \
&&  apt-get -y install curl libelf1 \
&&  apt-get clean

# Install Node.js, Yarn
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash - \
&&  apt-get install -y nodejs \
&&  curl -o- -sL https://yarnpkg.com/install.sh | bash -
ENV PATH /root/.yarn/bin/:$PATH

WORKDIR /myapp
